# Generated by Django 4.1.4 on 2023-05-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_friend_group_transactions_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
