# Generated by Django 4.1.4 on 2023-05-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactions_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.group'),
        ),
    ]
