# Generated by Django 4.1.4 on 2023-05-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transactions_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='group',
        ),
    ]
